[default.extend-words]
neet = "neet"
NEET = "NEET"
OT = "OT"
ETCC = "ETCC"
OLL = "OLL"
CLL = "CLL"
Yau = "Yau"
noice = "noice"
Noice = "Noice"
Dota = "Dota"
nd = "nd"
beastiality = "beastiality"

[default.extend-identifiers]
noice = "noice"
