theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = false
scrolloff = 4
middle-click-paste = false
auto-save = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "┊"

